services:
  rplay_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.rplay_server.rule=Host(`rplay.haniking.com`)
      - traefik.http.routers.rplay_server.entrypoints=web
      
networks:
  web:
    external: true